/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;


/**
 *
 * @author axel
 */
public class MenuLateralCoordinador_OperativoTaquillas extends javax.swing.JPanel {

    /**
     * Creates new form MenuLateralCoordinador_OperativoTaquillas
     */
    public MenuLateralCoordinador_OperativoTaquillas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        BotonInicio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        BotonAgendarVisitas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        BotonRegistrarVisitantes = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        BotonRegistrarEventos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        BotonMensajes = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(224, 229, 233));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo-3.png"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 220));

        BotonInicio.setBackground(new java.awt.Color(159, 195, 231));
        BotonInicio.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BotonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonInicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonInicioMouseExited(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Inicio");

        javax.swing.GroupLayout BotonInicioLayout = new javax.swing.GroupLayout(BotonInicio);
        BotonInicio.setLayout(BotonInicioLayout);
        BotonInicioLayout.setHorizontalGroup(
            BotonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonInicioLayout.setVerticalGroup(
            BotonInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonInicioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(BotonInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 249, 250, 50));

        BotonAgendarVisitas.setBackground(new java.awt.Color(159, 195, 231));
        BotonAgendarVisitas.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BotonAgendarVisitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAgendarVisitasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonAgendarVisitasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonAgendarVisitasMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Agendar Visitas");

        javax.swing.GroupLayout BotonAgendarVisitasLayout = new javax.swing.GroupLayout(BotonAgendarVisitas);
        BotonAgendarVisitas.setLayout(BotonAgendarVisitasLayout);
        BotonAgendarVisitasLayout.setHorizontalGroup(
            BotonAgendarVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonAgendarVisitasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonAgendarVisitasLayout.setVerticalGroup(
            BotonAgendarVisitasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonAgendarVisitasLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(BotonAgendarVisitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 250, 50));

        BotonRegistrarVisitantes.setBackground(new java.awt.Color(159, 195, 231));
        BotonRegistrarVisitantes.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BotonRegistrarVisitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegistrarVisitantesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegistrarVisitantesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegistrarVisitantesMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Registrar Visitantes");

        javax.swing.GroupLayout BotonRegistrarVisitantesLayout = new javax.swing.GroupLayout(BotonRegistrarVisitantes);
        BotonRegistrarVisitantes.setLayout(BotonRegistrarVisitantesLayout);
        BotonRegistrarVisitantesLayout.setHorizontalGroup(
            BotonRegistrarVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonRegistrarVisitantesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonRegistrarVisitantesLayout.setVerticalGroup(
            BotonRegistrarVisitantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonRegistrarVisitantesLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(BotonRegistrarVisitantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 250, 50));

        BotonRegistrarEventos.setBackground(new java.awt.Color(159, 195, 231));
        BotonRegistrarEventos.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        BotonRegistrarEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonRegistrarEventosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonRegistrarEventosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonRegistrarEventosMouseExited(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Registrar Eventos");

        javax.swing.GroupLayout BotonRegistrarEventosLayout = new javax.swing.GroupLayout(BotonRegistrarEventos);
        BotonRegistrarEventos.setLayout(BotonRegistrarEventosLayout);
        BotonRegistrarEventosLayout.setHorizontalGroup(
            BotonRegistrarEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonRegistrarEventosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        BotonRegistrarEventosLayout.setVerticalGroup(
            BotonRegistrarEventosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonRegistrarEventosLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel4)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        add(BotonRegistrarEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 50));

        BotonMensajes.setBackground(new java.awt.Color(159, 195, 231));
        BotonMensajes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonMensajesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotonMensajesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotonMensajesMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Mensajes");

        javax.swing.GroupLayout BotonMensajesLayout = new javax.swing.GroupLayout(BotonMensajes);
        BotonMensajes.setLayout(BotonMensajesLayout);
        BotonMensajesLayout.setHorizontalGroup(
            BotonMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotonMensajesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BotonMensajesLayout.setVerticalGroup(
            BotonMensajesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotonMensajesLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(15, 15, 15))
        );

        add(BotonMensajes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 250, -1));

        jButton1.setBackground(new java.awt.Color(195, 216, 245));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(64, 97, 150));
        jButton1.setText("CERRAR SESIÓN");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 610, 190, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAgendarVisitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgendarVisitasMouseClicked
        // TODO add your handling code here:
        JFrame ventanacontenedora = (JFrame) SwingUtilities.getWindowAncestor(this);

        if(ventanacontenedora != null){
            if(ventanacontenedora instanceof AgendarVisitas){
                System.out.print("El panel esta en inicioadmin");
            }else if(ventanacontenedora instanceof Mensajes || ventanacontenedora instanceof InicioAdmin || ventanacontenedora instanceof RegistrarVisitantes || ventanacontenedora instanceof RegistrarEventos){
                System.out.println("El panel esta en: "+ ventanacontenedora);
                ventanacontenedora.dispose();
                AgendarVisitas AV = new AgendarVisitas();
                AV.setVisible(true);

            }
        }
    }//GEN-LAST:event_BotonAgendarVisitasMouseClicked

    private void BotonAgendarVisitasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgendarVisitasMouseEntered
        // TODO add your handling code here:
        Color nuevoColor = new Color(16,106,182);
        BotonAgendarVisitas.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonAgendarVisitasMouseEntered

    private void BotonAgendarVisitasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAgendarVisitasMouseExited
        // TODO add your handling code here:
        Color nuevoColor = new Color(18,113,199);
        BotonAgendarVisitas.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonAgendarVisitasMouseExited

    private void BotonRegistrarVisitantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarVisitantesMouseClicked
        // TODO add your handling code here:
        JFrame ventanacontenedora = (JFrame) SwingUtilities.getWindowAncestor(this);

        if(ventanacontenedora != null){
            if(ventanacontenedora instanceof RegistrarVisitantes){
                System.out.print("El panel esta en inicioadmin");
            }else if(ventanacontenedora instanceof Mensajes || ventanacontenedora instanceof InicioAdmin  || ventanacontenedora instanceof AgendarVisitas || ventanacontenedora instanceof RegistrarEventos){
                System.out.println("El panel esta en: "+ ventanacontenedora);
                ventanacontenedora.dispose();
                RegistrarVisitantes RG = new RegistrarVisitantes();
                RG.setVisible(true);

            }
        }
    }//GEN-LAST:event_BotonRegistrarVisitantesMouseClicked

    private void BotonRegistrarVisitantesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarVisitantesMouseEntered
        // TODO add your handling code here:
        Color nuevoColor = new Color(16,106,182);
        BotonRegistrarVisitantes.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonRegistrarVisitantesMouseEntered

    private void BotonRegistrarVisitantesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarVisitantesMouseExited
        // TODO add your handling code here:
        Color nuevoColor = new Color(18,113,199);
        BotonRegistrarVisitantes.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonRegistrarVisitantesMouseExited

    private void BotonRegistrarEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarEventosMouseClicked
        // TODO add your handling code here:
        JFrame ventanacontenedora = (JFrame) SwingUtilities.getWindowAncestor(this);

        if(ventanacontenedora != null){
            if(ventanacontenedora instanceof RegistrarEventos){
                System.out.print("El panel esta en inicioadmin");
            }else if(ventanacontenedora instanceof Mensajes || ventanacontenedora instanceof InicioAdmin || ventanacontenedora instanceof RegistrarVisitantes || ventanacontenedora instanceof AgendarVisitas){
                System.out.println("El panel esta en: "+ ventanacontenedora);
                ventanacontenedora.dispose();
                RegistrarEventos RV = new RegistrarEventos();
                RV.setVisible(true);

            }
        }
    }//GEN-LAST:event_BotonRegistrarEventosMouseClicked

    private void BotonRegistrarEventosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarEventosMouseEntered
        // TODO add your handling code here:
        Color nuevoColor = new Color(16,106,182);
        BotonRegistrarEventos.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonRegistrarEventosMouseEntered

    private void BotonRegistrarEventosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonRegistrarEventosMouseExited
        // TODO add your handling code here:
        Color nuevoColor = new Color(18,113,199);
        BotonRegistrarEventos.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonRegistrarEventosMouseExited

    private void BotonInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseClicked
        // TODO add your handling code here:
        JFrame ventanacontenedora = (JFrame) SwingUtilities.getWindowAncestor(this);

        if(ventanacontenedora != null){
            if(ventanacontenedora instanceof InicioAdmin){
                System.out.print("El panel esta en inicioadmin");
            }else if(ventanacontenedora instanceof Mensajes || ventanacontenedora instanceof RegistrarVisitantes || ventanacontenedora instanceof RegistrarEventos || ventanacontenedora instanceof AgendarVisitas ){
                System.out.println("El panel esta en: "+ ventanacontenedora);
                ventanacontenedora.dispose();
                InicioAdmin iniadmin = new InicioAdmin();
                iniadmin.setVisible(true);

            }
        }
    }//GEN-LAST:event_BotonInicioMouseClicked

    private void BotonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseEntered
        // TODO add your handling code here:
        Color nuevoColor = new Color(16,106,182);
        BotonInicio.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonInicioMouseEntered

    private void BotonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonInicioMouseExited
        // TODO add your handling code here:
        Color nuevoColor = new Color(18,113,199);
        BotonInicio.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonInicioMouseExited

    private void BotonMensajesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMensajesMouseClicked
        // TODO add your handling code here:
        JFrame ventanacontenedora = (JFrame) SwingUtilities.getWindowAncestor(this);

        if(ventanacontenedora != null){
            if(ventanacontenedora instanceof Mensajes){
                System.out.print("El panel esta en Mensajes");
            }else if(ventanacontenedora instanceof AgendarVisitas   || ventanacontenedora instanceof RegistrarVisitantes || ventanacontenedora instanceof InicioAdmin || ventanacontenedora instanceof RegistrarEventos){
                System.out.println("El panel esta en: "+ ventanacontenedora);
                ventanacontenedora.dispose();
                Mensajes mensajes = new Mensajes();
                mensajes.setVisible(true);

            }
        }
    }//GEN-LAST:event_BotonMensajesMouseClicked

    private void BotonMensajesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMensajesMouseEntered
        // TODO add your handling code here:
        Color nuevoColor = new Color(16,106,182);
        BotonMensajes.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonMensajesMouseEntered

    private void BotonMensajesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonMensajesMouseExited
        // TODO add your handling code here:
        Color nuevoColor = new Color(18,113,199);
        BotonMensajes.setBackground(nuevoColor);
    }//GEN-LAST:event_BotonMensajesMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonAgendarVisitas;
    private javax.swing.JPanel BotonInicio;
    private javax.swing.JPanel BotonMensajes;
    private javax.swing.JPanel BotonRegistrarEventos;
    private javax.swing.JPanel BotonRegistrarVisitantes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
