/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;

import java.awt.Color;

/**
 *
 * @author jauregui
 */
public class VentanaRegistrarPersonal extends javax.swing.JPanel {

    /**
     * Creates new form VentanaRegistrarPersonal
     */
    public VentanaRegistrarPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        TxtFieldNombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelNombre4 = new javax.swing.JLabel();
        jLabelRFC = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelCURP = new javax.swing.JLabel();
        TxtFieldUsuario = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldContraseña = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        TxtFieldCURP = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        TxtFieldRFC = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        TxtFieldFechaContratacion = new javax.swing.JTextField();
        TxtFieldEdad = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jButtonRegistrar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(790, 470));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(195, 237, 246));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Registrar Personal");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setText("Nombre");

        TxtFieldNombre.setForeground(new java.awt.Color(204, 204, 204));
        TxtFieldNombre.setText("Ingresa el nombre");
        TxtFieldNombre.setBorder(null);
        TxtFieldNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtFieldNombreMousePressed(evt);
            }
        });
        TxtFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldNombreActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(195, 237, 246));
        jSeparator1.setForeground(new java.awt.Color(195, 237, 246));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsuario.setText("Usuario");

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContraseña.setText("Contraseña");

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFecha.setText("Fecha de Contratacion");

        jLabelNombre4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRFC.setText("RFC");

        jLabelEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEdad.setText("Edad");

        jLabelCURP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCURP.setText("CURP");

        TxtFieldUsuario.setForeground(new java.awt.Color(204, 204, 204));
        TxtFieldUsuario.setText("Ingresa el Usuario");
        TxtFieldUsuario.setBorder(null);
        TxtFieldUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtFieldUsuarioMousePressed(evt);
            }
        });
        TxtFieldUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldUsuarioActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(195, 237, 246));
        jSeparator2.setForeground(new java.awt.Color(195, 237, 246));

        jTextFieldContraseña.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldContraseña.setText("Ingrese la contraseña");
        jTextFieldContraseña.setBorder(null);
        jTextFieldContraseña.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextFieldContraseñaMousePressed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(195, 237, 246));
        jSeparator3.setForeground(new java.awt.Color(195, 237, 246));

        TxtFieldCURP.setForeground(new java.awt.Color(204, 204, 204));
        TxtFieldCURP.setText("Ingrese el CURP");
        TxtFieldCURP.setBorder(null);
        TxtFieldCURP.setPreferredSize(new java.awt.Dimension(78, 17));
        TxtFieldCURP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtFieldCURPMousePressed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(195, 237, 246));
        jSeparator4.setForeground(new java.awt.Color(195, 237, 246));

        TxtFieldRFC.setForeground(new java.awt.Color(204, 204, 204));
        TxtFieldRFC.setText("Ingrese el RFC");
        TxtFieldRFC.setBorder(null);
        TxtFieldRFC.setPreferredSize(new java.awt.Dimension(78, 17));
        TxtFieldRFC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtFieldRFCMousePressed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setBackground(new java.awt.Color(195, 237, 246));
        jSeparator6.setForeground(new java.awt.Color(195, 237, 246));

        jSeparator7.setBackground(new java.awt.Color(195, 237, 246));
        jSeparator7.setForeground(new java.awt.Color(195, 237, 246));

        TxtFieldFechaContratacion.setForeground(new java.awt.Color(204, 204, 204));
        TxtFieldFechaContratacion.setText("Fecha de Contratacion");
        TxtFieldFechaContratacion.setBorder(null);
        TxtFieldFechaContratacion.setPreferredSize(new java.awt.Dimension(106, 17));
        TxtFieldFechaContratacion.setSize(new java.awt.Dimension(106, 17));
        TxtFieldFechaContratacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtFieldFechaContratacionMousePressed(evt);
            }
        });

        TxtFieldEdad.setForeground(new java.awt.Color(204, 204, 204));
        TxtFieldEdad.setText("Ingrese la edad");
        TxtFieldEdad.setBorder(null);
        TxtFieldEdad.setPreferredSize(new java.awt.Dimension(78, 17));
        TxtFieldEdad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TxtFieldEdadMousePressed(evt);
            }
        });
        TxtFieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtFieldEdadActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(195, 237, 246));
        jSeparator8.setForeground(new java.awt.Color(195, 237, 246));

        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelRFC)
                            .addComponent(jLabelContraseña)
                            .addComponent(TxtFieldNombre)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelUsuario)
                            .addComponent(TxtFieldUsuario)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jLabelCURP)
                            .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(TxtFieldRFC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(TxtFieldCURP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator7))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelFecha)
                                    .addComponent(jLabelNombre4)
                                    .addComponent(TxtFieldFechaContratacion, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(jSeparator6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelEdad)
                                    .addComponent(TxtFieldEdad, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                    .addComponent(jSeparator8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addComponent(jButtonRegistrar)))))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelNombre)
                        .addGap(12, 12, 12)
                        .addComponent(TxtFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(jLabelUsuario)
                        .addGap(12, 12, 12)
                        .addComponent(TxtFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelContraseña)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelCURP)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFieldCURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelRFC)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtFieldRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFecha)
                        .addGap(12, 12, 12)
                        .addComponent(TxtFieldFechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelEdad)
                        .addGap(12, 12, 12)
                        .addComponent(TxtFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombre4)
                        .addGap(41, 41, 41)
                        .addComponent(jButtonRegistrar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TxtFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldNombreActionPerformed

    private void TxtFieldUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldUsuarioActionPerformed

    private void TxtFieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtFieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtFieldEdadActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void TxtFieldNombreMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtFieldNombreMousePressed
        // TODO add your handling code here:
        TxtFieldNombre.setText("");
        TxtFieldNombre.setForeground(Color.black);
    }//GEN-LAST:event_TxtFieldNombreMousePressed

    private void TxtFieldUsuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtFieldUsuarioMousePressed
        // TODO add your handling code here:
        TxtFieldUsuario.setText("");
        TxtFieldUsuario.setForeground(Color.black);
    }//GEN-LAST:event_TxtFieldUsuarioMousePressed

    private void jTextFieldContraseñaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldContraseñaMousePressed
        // TODO add your handling code here:
        jTextFieldContraseña.setText("");
        jTextFieldContraseña.setForeground(Color.black);
    }//GEN-LAST:event_jTextFieldContraseñaMousePressed

    private void TxtFieldCURPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtFieldCURPMousePressed
        // TODO add your handling code here:
        TxtFieldCURP.setText("");
        TxtFieldCURP.setForeground(Color.black);
    }//GEN-LAST:event_TxtFieldCURPMousePressed

    private void TxtFieldRFCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtFieldRFCMousePressed
        // TODO add your handling code here:
        TxtFieldRFC.setText("");
        TxtFieldRFC.setForeground(Color.black);
    }//GEN-LAST:event_TxtFieldRFCMousePressed

    private void TxtFieldFechaContratacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtFieldFechaContratacionMousePressed
        // TODO add your handling code here:
        TxtFieldFechaContratacion.setText("");
        TxtFieldFechaContratacion.setForeground(Color.black);
    }//GEN-LAST:event_TxtFieldFechaContratacionMousePressed

    private void TxtFieldEdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtFieldEdadMousePressed
        // TODO add your handling code here:
        TxtFieldEdad.setText("");
        TxtFieldEdad.setForeground(Color.black);
    }//GEN-LAST:event_TxtFieldEdadMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtFieldCURP;
    private javax.swing.JTextField TxtFieldEdad;
    private javax.swing.JTextField TxtFieldFechaContratacion;
    private javax.swing.JTextField TxtFieldNombre;
    private javax.swing.JTextField TxtFieldRFC;
    private javax.swing.JTextField TxtFieldUsuario;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCURP;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre4;
    private javax.swing.JLabel jLabelRFC;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTextField jTextFieldContraseña;
    // End of variables declaration//GEN-END:variables
}
