/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ventana;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JPanel;
import java.awt.CardLayout;
import java.awt.BorderLayout;
import javax.swing.*; 
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.ResultSet;
import java.sql.PreparedStatement;

/**
 *
 * @author jauregui
 */
public class VentanaRegistrarPersonal extends javax.swing.JPanel {
Conexion conect=new Conexion();
    Connection conectar=conect.estableceConexion();
    /**
     * Creates new form VentanaRegistrarPersonal
     */
    public VentanaRegistrarPersonal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        IdPersonal = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelContraseña = new javax.swing.JLabel();
        jLabelFecha = new javax.swing.JLabel();
        jLabelNombre4 = new javax.swing.JLabel();
        jLabelRFC = new javax.swing.JLabel();
        jLabelEdad = new javax.swing.JLabel();
        jLabelCURP = new javax.swing.JLabel();
        NombrePersonal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        CURP = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        RFCPersonal = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        FechaContratacion = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        Edad = new javax.swing.JTextField();
        IdRol = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jButtonRegistrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        IdReporte = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        IdItem = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(790, 470));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(195, 237, 246));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 97, 150));
        jLabel1.setText("Registrar Personal");

        jLabelNombre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNombre.setText("Identificador");

        IdPersonal.setForeground(new java.awt.Color(204, 204, 204));
        IdPersonal.setBorder(null);
        IdPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdPersonalMousePressed(evt);
            }
        });
        IdPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdPersonalActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator1.setForeground(new java.awt.Color(64, 97, 150));

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUsuario.setText("Nombre");

        jLabelContraseña.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelContraseña.setText("CURP");

        jLabelFecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelFecha.setText("Edad");

        jLabelNombre4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabelRFC.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRFC.setText("Fecha de contratación");

        jLabelEdad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEdad.setText("Identificador de rol");

        jLabelCURP.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCURP.setText("RFC");

        NombrePersonal.setForeground(new java.awt.Color(204, 204, 204));
        NombrePersonal.setBorder(null);
        NombrePersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                NombrePersonalMousePressed(evt);
            }
        });
        NombrePersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombrePersonalActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator2.setForeground(new java.awt.Color(64, 97, 150));

        CURP.setForeground(new java.awt.Color(204, 204, 204));
        CURP.setBorder(null);
        CURP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CURPMousePressed(evt);
            }
        });

        jSeparator3.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator3.setForeground(new java.awt.Color(64, 97, 150));

        RFCPersonal.setForeground(new java.awt.Color(204, 204, 204));
        RFCPersonal.setBorder(null);
        RFCPersonal.setPreferredSize(new java.awt.Dimension(78, 17));
        RFCPersonal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RFCPersonalMousePressed(evt);
            }
        });

        jSeparator4.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator4.setForeground(new java.awt.Color(64, 97, 150));

        FechaContratacion.setForeground(new java.awt.Color(204, 204, 204));
        FechaContratacion.setBorder(null);
        FechaContratacion.setPreferredSize(new java.awt.Dimension(78, 17));
        FechaContratacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                FechaContratacionMousePressed(evt);
            }
        });

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator6.setForeground(new java.awt.Color(64, 97, 150));

        jSeparator7.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator7.setForeground(new java.awt.Color(64, 97, 150));

        Edad.setForeground(new java.awt.Color(204, 204, 204));
        Edad.setBorder(null);
        Edad.setPreferredSize(new java.awt.Dimension(106, 17));
        Edad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                EdadMousePressed(evt);
            }
        });

        IdRol.setForeground(new java.awt.Color(204, 204, 204));
        IdRol.setBorder(null);
        IdRol.setPreferredSize(new java.awt.Dimension(78, 17));
        IdRol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IdRolMousePressed(evt);
            }
        });
        IdRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdRolActionPerformed(evt);
            }
        });

        jSeparator8.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator8.setForeground(new java.awt.Color(64, 97, 150));

        jButtonRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Registrar.png"))); // NOI18N
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Identificador de reporte");

        jSeparator9.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator9.setForeground(new java.awt.Color(64, 97, 150));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Identificador de item");

        jSeparator10.setBackground(new java.awt.Color(64, 97, 150));
        jSeparator10.setForeground(new java.awt.Color(64, 97, 150));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Regresar.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(188, 188, 188))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabelRFC)
                            .addComponent(jLabelContraseña)
                            .addComponent(IdPersonal)
                            .addComponent(jLabelNombre)
                            .addComponent(jLabelUsuario)
                            .addComponent(NombrePersonal)
                            .addComponent(jSeparator2)
                            .addComponent(jSeparator1)
                            .addComponent(jLabelCURP)
                            .addComponent(CURP, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(FechaContratacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3)
                            .addComponent(RFCPersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator7))
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(190, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(IdItem)
                                        .addGap(188, 188, 188))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabelFecha)
                                            .addComponent(jLabelNombre4)
                                            .addComponent(Edad, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                            .addComponent(jSeparator6)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelEdad)
                                            .addComponent(IdRol, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                                            .addComponent(jSeparator8)
                                            .addComponent(IdReporte)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton1))
                                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelNombre)
                                .addGap(12, 12, 12)
                                .addComponent(IdPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(jLabelUsuario)
                                .addGap(12, 12, 12)
                                .addComponent(NombrePersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelContraseña)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CURP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCURP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RFCPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelRFC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FechaContratacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelFecha)
                        .addGap(12, 12, 12)
                        .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelEdad)
                        .addGap(12, 12, 12)
                        .addComponent(IdRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IdReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelNombre4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(IdItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(11, 11, 11))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void Guardar(){
    String IdPr = IdPersonal.getText();
    String Nombre =NombrePersonal.getText();
    String clave=CURP.getText();
    String RFC=RFCPersonal.getText();
    String Fecha=FechaContratacion.getText();
    String edadper= Edad.getText();
      String idr= IdRol.getText();
        String idrep= IdReporte.getText();
          String idi= IdItem.getText();
          
    String sql="Insert into Personal () values (?,?,?,?,?,?,?,?,?)";
    try{
    Statement st=conectar.createStatement();
    ResultSet resultado= st.executeQuery("select * from Personal where ID like'"+IdPersonal.getText()+"'");
    if (resultado.next()){
    getToolkit().beep();
    JOptionPane.showMessageDialog(null, "Ese identificador ya está ocupado");
    IdPersonal.requestFocus();
            } else if(IdPersonal.getText().isEmpty()){
            getToolkit().beep();
    JOptionPane.showMessageDialog(null, "Ingrese un identificador");
    IdPersonal.requestFocus();
            } else{
            
            PreparedStatement pasardatos =conectar.prepareStatement(sql);
            
            pasardatos.setString(1, IdPr);
            pasardatos.setString(2, Nombre);
            pasardatos.setString(3, clave);
            pasardatos.setString(4, RFC);
            pasardatos.setString(5, Fecha);
            pasardatos.setString(6, edadper);
            pasardatos.setString(7, idr);
            pasardatos.setString(8, idrep);
            pasardatos.setString(9, idi);
            pasardatos.executeUpdate();
            JOptionPane.showMessageDialog(null, "Registro exitoso");
   
            }
    
    }catch (SQLException e){
        Logger.getLogger(VentanaRegistrarItem.class.getName()).log(Level.SEVERE, null, e);
    }
    
    }
    
    
    private void IdPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdPersonalActionPerformed

    private void NombrePersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombrePersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombrePersonalActionPerformed

    private void IdRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdRolActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
Guardar();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegistrarActionPerformed

    private void IdPersonalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdPersonalMousePressed
        // TODO add your handling code here:
        IdPersonal.setText("");
        IdPersonal.setForeground(Color.black);
    }//GEN-LAST:event_IdPersonalMousePressed

    private void NombrePersonalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_NombrePersonalMousePressed
        // TODO add your handling code here:
        NombrePersonal.setText("");
        NombrePersonal.setForeground(Color.black);
    }//GEN-LAST:event_NombrePersonalMousePressed

    private void CURPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CURPMousePressed
        // TODO add your handling code here:
        CURP.setText("");
        CURP.setForeground(Color.black);
    }//GEN-LAST:event_CURPMousePressed

    private void RFCPersonalMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RFCPersonalMousePressed
        // TODO add your handling code here:
        RFCPersonal.setText("");
        RFCPersonal.setForeground(Color.black);
    }//GEN-LAST:event_RFCPersonalMousePressed

    private void FechaContratacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FechaContratacionMousePressed
        // TODO add your handling code here:
        FechaContratacion.setText("");
        FechaContratacion.setForeground(Color.black);
    }//GEN-LAST:event_FechaContratacionMousePressed

    private void EdadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EdadMousePressed
        // TODO add your handling code here:
        Edad.setText("");
        Edad.setForeground(Color.black);
    }//GEN-LAST:event_EdadMousePressed

    private void IdRolMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IdRolMousePressed
        // TODO add your handling code here:
        IdRol.setText("");
        IdRol.setForeground(Color.black);
    }//GEN-LAST:event_IdRolMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Personal newframe = new Personal();
        newframe.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CURP;
    private javax.swing.JTextField Edad;
    private javax.swing.JTextField FechaContratacion;
    private javax.swing.JTextField IdItem;
    private javax.swing.JTextField IdPersonal;
    private javax.swing.JTextField IdReporte;
    private javax.swing.JTextField IdRol;
    private javax.swing.JTextField NombrePersonal;
    private javax.swing.JTextField RFCPersonal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCURP;
    private javax.swing.JLabel jLabelContraseña;
    private javax.swing.JLabel jLabelEdad;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre4;
    private javax.swing.JLabel jLabelRFC;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    // End of variables declaration//GEN-END:variables
}
